implement asset active region in audiotrack playback mechanism
loafofpiecrust/roundware-ios-framework-v2 pull request #14
Opened 2019-04-01 23:25 UTC by hburgund

2019-04-26 01:04 UTC, hburgund commented
This PR is now ready for your review @loafofpiecrust

2019-04-27 12:11 UTC, loafofpiecrust approved these changes

2019-04-27 12:11 UTC, loafofpiecrust commented on RWFramework/RWFramework/Playlist/Playlist.swift
> +        audioMixer.renderingAlgorithm = .HRTFHQ
This PR works fine for me except the `HRTFHQ` rendering doesn't seem to work in the simulator (😭 ) but if it works on device, then this is all set.

2019-04-27 12:27 UTC, loafofpiecrust requested changes

2019-04-27 12:27 UTC, loafofpiecrust commented on RWFramework/RWFramework/Playlist/Playlist.swift
> +                it.player.renderingAlgorithm = .HRTFHQ
We need to remove this line entirely. It's unnecessary and messes up for me with `.HRTFHQ`.
```suggestion
```

2019-04-29 03:30 UTC, hburgund commented
@loafofpiecrust I have rebased in the change you requested after testing on my end, so this should be good to merge now, I think

2019-04-30 15:37 UTC, loafofpiecrust approved these changes

2019-04-30 15:38 UTC, merged